### ISSUE TITLE
Test Plan no sort

### ISSUE THREAD

**Issue by ShockwaveNN** [flaminestone/palladium-view#40]
![image](https://user-images.githubusercontent.com/668524/30531548-bf7b0ed4-9c57-11e7-9188-8ca8dad00ac3.png)

**Comment by ShockwaveNN** [comment]
Dont understand login.
I'm sure, that build 15 was created earlier than build 115
So this is not `sorted by creation` and also not `sorted by name`

**Comment by flaminestone** [comment]
Fixed. Now plans will be sorted by created_at date
